#!/usr/bin/env bash

if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    . "$(brew --prefix)/etc/bash_completion"
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f ~/.shrc ]; then
	source ~/.shrc
fi
