#!/usr/bin/env bash

# Run cross shell configuration
. ~/.shrc

HISTFILE="$XDG_STATE_HOME/bash/history"
mkdir -p "$XDG_STATE_HOME/bash" # bash doesn't create it

if type brew 1>/dev/null 2>&1; then
	# Set up completions for `brew` command and `brew`-installed programs
	# See: https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash
	HOMEBREW_PREFIX="$(brew --prefix)"
	if [ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]; then
		. "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
	else
		for completion in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
			if [ -r "${COMPLETION}" ]; then
				. "${COMPLETION}"
			fi
		done
	fi
fi

# Set up Google Cloud SDK
if command -v gcloud >/dev/null 2>&1; then
	. "$(brew --prefix)/share/google-cloud-sdk/path.bash.inc"
	. "$(brew --prefix)/share/google-cloud-sdk/completion.bash.inc"
fi

# Enable searching shell history with fzf
if [ -f ~/.fzf.bash ]; then
	. ~/.fzf.bash
fi

. "$HOME/.dotfiles/script/aliases"
