brew 'apktool'
brew 'avrdude'
brew 'bash'
brew 'bat'
brew 'clang-format'
brew 'cmake'
brew 'coreutils'
brew 'croc'
brew 'doxygen'
brew 'duti'
brew 'exif'
brew 'exiftool'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'gh'
brew 'git-filter-repo'
brew 'git-lfs'
brew 'git'
brew 'go'
brew 'gofumpt'
brew 'gpg'
brew 'gradle'
brew 'grep'
brew 'htop'
brew 'ideviceinstaller'
brew 'imagemagick'
brew 'ios-deploy'
brew 'iproute2mac'
brew 'jq'
brew 'latexindent'
brew 'lcov'
brew 'less'
brew 'libimobiledevice'
brew 'lsd'
brew 'mas'
brew 'maven'
brew 'micro'
brew 'moreutils'
brew 'mosh'
brew 'mycli'
brew 'n' if false # Still deciding between nvm and n
brew 'ncdu'
brew 'neofetch'
brew 'nmap'
brew 'nvm' if false # Still deciding between nvm and n
brew 'openjdk'
brew 'pgcli'
brew 'poetry' if false # use poetry installed by pip from pyenv, see https://github.com/Homebrew/homebrew-core/issues/53169
brew 'purr'
brew 'pyenv'
brew 'rbenv'
brew 'rg'
brew 'rustup'
brew 'shellcheck'
brew 'shfmt'
brew 'swift-format'
brew 'tealdeer'
brew 'texlive'
brew 'tmux'
brew 'tree'
brew 'webp'
brew 'wget'
brew 'xcbeautify'
brew 'yq'
brew 'zsh'

cask '1password-cli'
cask '1password'
cask 'daisydisk'
cask 'discord'
cask 'docker'
cask 'firefox'
cask 'ghostty'
cask 'gimp'
cask 'keystore-explorer'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'mos'
cask 'notion'
cask 'qlimagesize' if false # does not work on newer macOS version. TODO: try to make it work
cask 'qlstephen' if false # does not work on newer macOS version. TODO: try to make it work
cask 'quicklook-json' if false # does not work on newer macOS version. TODO: try to make it work
cask 'quicklookapk' if false # does not work on newer macOS version. TODO: try to make it works
cask 'raspberry-pi-imager' if false # TODO: learn how to flash with built-in tools
cask 'slack'
cask 'tailscale'
cask 'utm'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
cask 'zoom'

# Specific taps

tap 'bartekpacia/tools'
brew 'emu'
brew 'fhome'
brew 'fhomed'
brew 'scripts'

tap 'tinygo-org/tools'
brew 'tinygo'

tap 'homebrew/cask-fonts'
cask 'font-jetbrains-mono'

# Font needed by lsd
cask 'font-hack-nerd-font'

tap 'dart-lang/dart'
brew 'dart' if false # I use Dart that comes with Flutter

tap 'leoafarias/fvm'
brew 'fvm'

tap 'facebook/fb'
brew 'idb-companion'

tap 'osx-cross/avr' if false # almost never used
brew 'avr-gcc' if false  # almost never used

tap 'ArmMbed/homebrew-formulae' if false # almost never used
brew 'arm-none-eabi-gcc' if false # almost never used

mas 'Amphetamine', id: 937984704 if false # almost never used
mas 'iMovie', id: 408981434
mas 'Keynote', id: 409183694
mas 'LocalSend', id: 1661733229
mas 'Notability', id: 360593530
mas 'Numbers', id: 361304891
mas 'Pages', id: 409201541
mas 'Telegram', id: 747648890
mas 'Termius - SSH client', id: 1176074088 if false # almost never used
mas 'The Unarchiver', id: 425424353
mas 'Xcode', id: 497799835
