brew 'bat'
brew 'cocoapods'
brew 'ffmpeg'

brew 'gh'
brew 'git'
brew 'go'
brew 'grep'
brew 'htop'

brew 'imagemagick'
brew 'ios-deploy'

brew 'kotlin'
brew 'ktlint'

brew 'lsd'

brew 'neofetch'
brew 'nmap'
brew 'nvm'

brew 'pyenv'

brew 'rbenv'
brew 'realpath'

brew 'webp'
brew 'zsh'

cask 'brooklyn'
cask 'daisydisk'
cask 'google-chrome'
cask 'discord'
cask 'gimp'
cask 'gitkraken'
cask 'iterm2'
cask 'java'
cask 'jetbrains-toolbox'
brew 'mas'
cask 'postman'
cask 'skype'
cask 'spotify'
cask 'sf-symbols'
cask 'qlimagesize'
cask 'qlstephen'
cask 'quicklook-json'
cask 'quicklookapk'
cask 'visual-studio-code'

# Specific taps

# OpenJDK 8 for use with android-studio
tap 'AdoptopenJDK/openjdk'
cask 'adoptopenjdk8'

# Font needed by lsd
tap 'homebrew/cask-fonts'
cask 'font-hack-nerd-font'
cask 'font-jetbrains-mono'

tap 'heroku/brew'
brew 'heroku'

tap 'dart-lang/dart'
brew 'dart'

tap 'teamookla/speedtest'
brew 'speedtest'

mas 'Keynote', id: 409183694
mas 'Evernote', id: 406056744
mas 'Messenger', id: 1480068668
mas 'Notability', id: 736189492
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Telegram', id: 747648890
mas 'Slack', id: 803453959
mas 'iMovie', id: 408981434
mas 'Xcode', id: 497799835


