#!/usr/bin/env sh
# cross-shell configuration

stty -echoctl

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export DOTFILES="$HOME/.dotfiles"

if [ -x /opt/homebrew/bin/brew ]; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
	export HOMEBREW_NO_ENV_HINTS=1
	export HOMEBREW_NO_AUTO_UPDATE=1
	export HOMEBREW_NO_INSTALL_CLEANUP=1
fi

# GPG config (see https://help.github.com/en/github/authenticating-to-github/telling-git-about-your-signing-key)
GPG_TTY=$(tty)
export GPG_TTY

# 1Password SSH agent config
# This points to a symlink. The real socket is in "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"

# Dart executable packages
export PATH="$HOME/.pub-cache/bin:$PATH"

export PATH="$HOME/projects/starpls/editors/code/bin:$PATH"

# Flutter
export PATH="$HOME/fvm/default/bin:$PATH" # installed with fvm
export PATH="$HOME/flutter/bin:$PATH" # installed directly
export PATROL_NO_COMPLETION=true

# Check if depot_tools is installed and DEPOT_TOOLS_ENABLED is set
if [ -d "$HOME/depot_tools" ] && [ -n "$DEPOT_TOOLS_ENABLED" ]; then
    export PATH="$HOME/depot_tools:$PATH"
fi

# Android

# see https://developer.android.com/studio/command-line/variables
export ANDROID_HOME="$HOME/androidsdk"
export ANDROID_USER_HOME="$HOME/.android"
# see https://developer.android.com/studio/command-line#tools-sdk
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
# see https://developer.android.com/studio/command-line#tools-platform
export PATH="$ANDROID_HOME/platform-tools:$PATH"
# see https://developer.android.com/studio/command-line#tools-emulator
export PATH="$ANDROID_HOME/emulator:$PATH"

if [ -d "$ANDROID_HOME/build-tools" ]; then
	build_tools=$(
		command ls "$ANDROID_HOME/build-tools" |
			sort --version-sort --reverse |
			head -n 1
	)
	export PATH="$ANDROID_HOME/build-tools/$build_tools:$PATH"
fi

# Raspberry Pi Pico
export PICO_SDK_PATH="$HOME/pico-sdk"

# Java
if [ "$(uname)" = Linux ]; then
	# on Linux
	# Download: https://github.com/adoptium/temurin17-binaries/releases
  # Install: https://adoptium.net/en-GB/installation/archives
  # Look for "OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz"
	export JAVA_HOME="/usr/lib/jvm/temurin-17.jdk"
	export PATH="$JAVA_HOME/bin:$PATH"
elif [ "$(uname)" = Darwin ]; then
	# on macOS
	export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
	export PATH="$JAVA_HOME/bin:$PATH"
fi

# Docker
export DOCKER_CLI_HINTS=false
# not needed anymore???
# export PATH="$HOME/.docker/bin:$PATH"


# Gradle
export GRADLE_USER_HOME="$HOME/.gradle"

# Vagrant
export VAGRANT_HOME="$XDG_DATA_HOME/vagrant"

# dotnet
export PATH="/usr/local/share/dotnet/x64:$PATH"
export PATH="$HOME/.dotnet/tools:$PATH"

# make
export MAKEFLAGS="-j 8"

# avr-gcc
export PATH="/usr/local/opt/avr-gcc@11/bin:$PATH"

# Maestro
export PATH="$PATH:$HOME/.maestro/bin"

# Python poetry
export VENV_PATH="$HOME/.venvs"
export PATH="$VENV_PATH/bin:$PATH"

# Check if pyenv is installed
if [ -d "$HOME/.pyenv" ]; then
	eval "$(pyenv init --path)"
	eval "$(pyenv init -)"
fi
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUSERBASE="$XDG_DATA_HOME/python"
export JUPYTER_PLATFORM_DIRS=1

# Ruby

# Check if rbenv is installed
if [ -d "$HOME/.rbenv" ]; then
	export PATH="$HOME/.rbenv/bin:$PATH"
	eval "$(rbenv init -)"
fi

# Node.js
export NODE_REPL_HISTORY=""
export N_PREFIX="$HOME/.n"
export PATH="$HOME/.n/bin:$PATH"

# Go

# when Go installed directly from the webpage (no thru the pkg manager)
export PATH="/usr/local/go/bin:$PATH"
# for "go install"-ed software
export PATH="$HOME/go/bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# https://github.com/bartekpacia/scripts (when not installed through brew)
if [ -d "$HOME/scripts" ]; then
	export PATH="$HOME/scripts/bin:$PATH"
fi

# TealDeer
export TEALDEER_CONFIG_DIR="$HOME/.config/tealdeer"

# Wolfram Mathematica
if [ "$(uname)" = Darwin ]; then
	export PATH="/Applications/Mathematica.app/Contents/MacOS:$PATH"
fi

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Preferred editor for local and remote sessions
if [ -n "$SSH_CONNECTION" ]; then
	export EDITOR=micro
else
	export EDITOR=micro
fi

# Add local gitignored files to PATH
if [ -d "$DOTFILES/local" ]; then
	export PATH="$DOTFILES/local:$PATH"
fi

# bat
if command -v bat >/dev/null 2>&1; then
	export BAT_CONFIG_PATH="$HOME/.bat.conf"
	alias batt="bat --theme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo default || echo GitHub)"
	# colorize man pages using bat
	export MANPAGER="sh -c 'col -bx | bat -l man -p'"
	# fix formatting problems (so far I experienced it only on ArchLinux)
	export MANROFFOPT="-c"
	# use bat for brew cat
	if command -v brew >/dev/null 2>&1; then
		export HOMEBREW_BAT=1
	fi
fi

export LESSHISTFILE="$XDG_DATA_HOME/less/history" # make less not clutter ~
export CP_HOME_DIR="$XDG_CACHE_HOME/cocoapods"    # make cocoapods not clutter ~
export MASON_CACHE="$XDG_CACHE_HOME/.cache/mason" # make mason not clutter ~
export MAVEN_HOME="$XDG_CACHE_HOME/.cache/maven"  # make maven not clutter ~
