# TODO: decide if this is really needed
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# if command -v pyenv &>/dev/null; then
#    eval "$(pyenv init --path)"
#    export PATH="$PYENV_ROOT/shims:$PATH"
# fi

if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
