#!/usr/bin/env zsh

# Run cross shell configuration
source ~/.shrc

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CONFIG="$HOME/.zshrc"
export ZSH_CUSTOM="$ZSH/custom"
export ZSH_COMPDUMP="$ZSH_CACHE_DIR/.zcompdump-$SHORT_HOST-$ZSH_VERSION"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
mkdir -p "$XDG_STATE_HOME/zsh" # zsh doesn't create it

export MLH_AT_SYMBOL=" at "
export MLH_IN_SYMBOL=" in "
export MLH_ON_SYMBOL=" on "
export MLH_SHELL_SYMBOL="$ "

ZSH_THEME="mlh"
# ohmyzsh: use case-sensitive completion
CASE_SENSITIVE="true"

plugins=(
	1password
	adb
	brew
	# docker - works automatically when brew-installed
	# dotnet
	`#fzf` $([ -x "$(command -v fzf)" ] && echo 'fzf')
	# flutter
	# gradle
	gradle-completion
	macos
	pod
	swiftpm
	terraform
	zsh-autosuggestions
	zsh-syntax-highlighting
)

if command -v brew >/dev/null 2>&1; then
	# Set up completions for `brew` command and `brew`-installed programs
	# See: https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
	FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"

	# Set up zsh-completions
	FPATH="$(brew --prefix)/share/zsh-completions:$FPATH"
fi

if [ -d "$ZSH" ]; then
	source "$ZSH/oh-my-zsh.sh"
	# oh-my-zsh initializes completion, so shrc needs to be sourced before it.
	# oh-my-zsh sets aliases, so aliases needs to be sourced after it.
	FPATH="$ZSH_CACHE_DIR/completions:$FPATH"
fi

# make CMD+Delete delete line before the cursor (not the whole line)
bindkey \^U backward-kill-line

# Auto-insert first completion https://unix.stackexchange.com/q/12288/417321
setopt menu_complete
# Disable the annoying beep
unsetopt beep

# Load cross-shell aliases
source "$HOME/.dotfiles/script/aliases"
