#!/usr/bin/env zsh

if [ -f ~/.shrc ]; then
	source ~/.shrc
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CONFIG="$HOME/.zshrc"
export ZSH_CUSTOM="$ZSH/custom"
export ZSH_COMPDUMP="$ZSH_CACHE_DIR/.zcompdump-$SHORT_HOST-$ZSH_VERSION"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"

export MLH_AT_SYMBOL=" at "
export MLH_IN_SYMBOL=" in "
export MLH_ON_SYMBOL=" on "
export MLH_SHELL_SYMBOL="$ "

ZSH_THEME="mlh"

plugins=(
	adb
	brew
	docker
	gh
	git
	gradle
	macos
	nvm
	pod
	zsh-autosuggestions
	zsh-syntax-highlighting
	# zsh-completions # needlessly slow, see https://github.com/zsh-users/zsh-completions/issues/603
 swiftpm)
# see https://github.com/zsh-users/zsh-completions/issues/603
fpath+="${ZSH_CUSTOM:-"$ZSH/custom"}/plugins/zsh-completions/src"


# lazy nvm configuration, see https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/nvm
zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript

if command -v brew >/dev/null 2>&1; then
	fpath+="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

if [ -d "$ZSH" ]; then
	source "$ZSH/oh-my-zsh.sh"
fi

zstyle ':completion:*' matcher-list ''
bindkey \^U backward-kill-line

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
