#!/usr/bin/env bash
set -euo pipefail

# disable_chime disables the annoying noise that macOS does by default when
# starting up.

sudo nvram StartupMute=%01
echo "disable_chime: the startup chime was disabled"
