#!/bin/bash

set -euo pipefail

o=$(python3 -c $'import os\nprint(os.get_blocking(0))\nos.set_blocking(0, True)')

ARCH=$(uname -m)

if [ "$ARCH" = "x86_64" ]; then
  ARCH=amd64
fi

#Download Latest Go
GOURLREGEX="https://dl.google.com/go/go[0-9\.]+\.linux-$ARCH).tar.gz"
echo "Finding latest version of Go for AMD64..."
GREPPABLE="https:\/\/dl\.google\.com\/go\/go([0-9\.]+)\.linux-$ARCH\.tar\.gz"
echo $GREPPABLE
url="$(wget -qO- https://golang.org/dl/ | ggrep -oP $GREPPABLE | head -n 1 )"
latest="$(echo $url | ggrep -oP 'go[0-9\.]+' | ggrep -oP '[0-9\.]+' | head -c -2 )"
echo "Downloading latest Go for AMD64: ${latest}"
wget --quiet --continue --show-progress "${url}"
unset url
unset GOURLREGEX


# Print Go Version
/usr/local/go/bin/go version
python3 -c $'import os\nos.set_blocking(0, '$o')'
