#!/usr/bin/env bash
set -euo pipefail

# Installs my Ubuntu packages. Run with sudo.

apt update
apt upgrade
apt autoremove -y

SOFTWARE=(
    git
    htop
    imagemagick
    neofetch
    python3
    zsh
)

apt install -y $(SOFTWARE)
