#!/bin/bash
set -e

# This script is designed to be run as part of the strap bootstrapping process.
# Assume that git and brew are installed. Assume that dotfiles repo is in ~.

# Symlink dot/* into home directory as hidden files
for f in $(ls -d ~/dotfiles/dot/*); do
  ln -sfn $f ~/.$(basename $f);
done

# Symlink files/* into home directory as regular files
for f in $(ls -d ~/dotfiles/files/*);
  do ln -sfn $f ~/$(basename $f);
done

# Setup oh-my-zsh
export KEEP_ZSHRC="yes"
export RUNZSH="no"
if [ ! -d ~/.oh-my-zsh ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  echo "setup: Aborted installation of OhMyZsh because directory ~/.oh-my-zsh/ already exists."
fi

echo "setup: Copying your config..."

for f in $(ls -d ~/dotfiles/custom/plugins/*); do
  echo "setup: Symlinking $(basename $f)"
  ln -sfn $f ~/.oh-my-zsh/custom/plugins/$(basename $f)
done

for f in $(ls -d ~/dotfiles/custom/themes/*); do
  echo "setup: Symlinking $(basename $f)"
  ln -sfn $f ~/.oh-my-zsh/custom/themes/$(basename $f)
done

echo "setup: Symlinking bartekpacia.zsh"
ln -sfn ~/.dotfiles/custom/bartekpacia.zsh ~/.oh-my-zsh/custom/bartekpacia.zsh

# The below asks for a password, so it's annoying
#
# echo "Changing default shell to zsh in $(which zsh)"
# chsh -s $(which zsh)
# echo "Successfully changed default shell to zsh"

echo "setup: such successfullness"