#!/usr/bin/env sh
set -eu

# setup_default_apps sets the default apps for specific UTI identifiers the way
# I want.
#
# See also:
# * https://developer.apple.com/documentation/uniformtypeidentifiers/uttype
# * `osascript -e 'id of app "Code"'` to get id of Visual Studio Code

duti -s com.microsoft.VSCode public.xml all
duti -s com.microsoft.VSCode public.shell-script all
duti -s com.microsoft.VSCode public.json all
duti -s com.microsoft.VSCode public.yaml all
duti -s com.microsoft.VSCode com.topografix.gpx all
duti -s com.microsoft.VSCode net.daringfireball.markdown all
duti -s com.microsoft.VSCode public.ruby-script all
duti -s org.mozilla.firefox com.adobe.pdf all
duti -s com.apple.Preview public.heic all
duti -s com.apple.Preview public.heif all

###
# Future idea: automate setup of default settings
# Inspired by: https://github.com/mathiasbynens/dotfiles/blob/master/.macos
###

# Finder: show hidden files by default
#defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# This works, but for changes to become effective, you need to re-login.
# See https://stackoverflow.com/q/3446128/7009800
defaults write ~/Library/Preferences/.GlobalPreferences.plist 'com.apple.keyboard.fnState' -bool true

# defaults write "com.apple.finder" "NewWindowTargetPath" '"file:///Users/bartek/Downloads/"'

###
# TEXT EDITING
###

# Set fast Key Repeat Rate and short Delay Until Repeat
# See https://apple.stackexchange.com/a/83923/333067
defaults write -g KeyRepeat -int 2 # the lowest value available in UI
defaults write -g InitialKeyRepeat -int 15 # the lowest value available in UI

# Disable inline attachments (just show the icons)
# stopped working for some reason
# defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

# Disable automatic capitalization as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
