#!/usr/bin/env sh
set -eu

# setup_default_apps creates files with credentials for various programs.
#
# It assumes that 1Password CLI is installed and set up.

if ! command -v op >/dev/null 2>&1; then
	echo "op command (1Password) CLI is not installed"
	exit 1
fi
