#!/usr/bin/env sh
set -eu

# setup_default_apps creates files with credentials for various programs.
#
# It assumes that 1Password CLI is installed and set up.

# shpotify (https://github.com/hnarayanan/shpotify)

if ! command -v op >/dev/null 2>&1; then
	echo "op command (1Password) CLI is not installed"
	exit 1
fi

shpotify_cfg_path="$HOME/.shpotify.cfg"
cat <<EOF >"$shpotify_cfg_path"
CLIENT_ID="$(op read 'op://Personal/Spotify/Client ID')"
CLIENT_SECRET="$(op read 'op://Personal/Spotify/Client secret')"
EOF

echo "$shpotify_cfg_path"
