#!/bin/bash

defaults delete com.apple.dock persistent-apps

dock_item() {
    printf '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>%s</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>', "$1"
}

defaults write com.apple.dock persistent-apps -array \
"$(dock_item /Applications/1Password\ 7.app)" \
"$(dock_item /Applications/Safari.app)" \
"$(dock_item /Applications/Google\ Chrome.app)" \
`# mail` \
`# calendar` \
"$(dock_item /Applications/Telegram.app)" \
"$(dock_item /Applications/Slack.app)" \
"$(dock_item /Applications/Discord.app)" \
"$(dock_item /Applications/Notion.app)" \
"$(dock_item /Applications/Spotify.app)" \
"$(dock_item /Applications/iTerm.app)" \
"$(dock_item /Applications/Visual\ Studio\ Code.app)" \

killall Dock
