#!/usr/bin/env bash
set -euo pipefail

# Stuff to happen after brew is installed goes here!

~/.dotfiles/script/disable_chime
~/.dotfiles/script/setup_default_apps
~/.dotfiles/script/setup_dock

echo "strap-after-setup: such successfullness"
