#!/bin/bash

input_files=$@

if [ $(echo "$1" | head -c 3) = "ic_" ]; then
  filename=$(printf "$1" | cut -d. -f1)
  echo "$filename"
  convert "$filename.png" -resize 512x512 -quality 70% "$filename.webp"
  exit 0
fi

for item in $input_files; do
  filename=$(printf "$item" | cut -d. -f1)
  echo "$filename"
  
  convert "$filename.jpg" -quality 68% -scale 25% "$filename.webp"
done
