#!/bin/bash

convargs="- unsharp 0x.5 -resize"
count=0
exact=""
fit=""

usage() {
    echo "Usage: $(basename $0) (-e|-f) thumb_size image [image] [image]"
}

if [ $# -eq 0]; then
  usage
fit

# TODO Finish