#!/bin/bash

convargs="- unsharp 0x.5 -resize"
count=0
exact=""
fit=""

usage() {
    echo "Użycie: $(basename $0) (-e|-f) wielkość_miniatury obraz [obraz] [obraz]"
}

if [ $# -eq 0]; then
  usage
fit

# TODO Finish